### ISSUE TITLE
Error: Cannot resolve module '@angular/core'

### ISSUE THREAD

**Issue by karlbunnell** [oprokidnev/ng2-fabricjs-skelton#1]
Thanks for putting this together! I'm trying to test drive this and when I start the server I get the following (any ideas on how to resolve this!):

ERROR in ./src/app.ts
Module build failed: Error: Cannot resolve module '@angular/core' in /Users/karlbunnell/code/ng2-fabricjs-skelton/node_modules/ng2-uploader/src/services
    Required in /Users/karlbunnell/code/ng2-fabricjs-skelton/node_modules/ng2-uploader/src/services/ng2-uploader.ts
    at ResolutionError.Error (native)
    at new ResolutionError (/Users/karlbunnell/code/ng2-fabricjs-skelton/node_modules/awesome-typescript-loader/dist.babel/deps.js:497:88)
    at /Users/karlbunnell/code/ng2-fabricjs-skelton/node_modules/awesome-typescript-loader/dist/deps.js:164:33
 @ multi app

ERROR in [default] /Users/karlbunnell/code/ng2-fabricjs-skelton/node_modules/ng2-uploader/src/directives/ng-file-drop.ts:1:50 
Cannot find module '@angular/core'.

ERROR in [default] /Users/karlbunnell/code/ng2-fabricjs-skelton/node_modules/ng2-uploader/src/directives/ng-file-select.ts:1:50 
Cannot find module '@angular/core'.

ERROR in [default] /Users/karlbunnell/code/ng2-fabricjs-skelton/node_modules/ng2-uploader/src/services/ng2-uploader.ts:1:39 
Cannot find module '@angular/core'.

ERROR in [default] /Users/karlbunnell/code/ng2-fabricjs-skelton/src/app.ts:13:7 
Property 'ImageSelectorApp' does not exist on type 'Window'.

ERROR in [default] /Users/karlbunnell/code/ng2-fabricjs-skelton/src/app.ts:14:8 
Type '{ uploadUrl: string; saveUrl: string; onFinish: any; baseUrl: string; }' is not assignable to type 'UrlSet'.
  Property 'gender' is missing in type '{ uploadUrl: string; saveUrl: string; onFinish: any; baseUrl: string; }'.

**Comment by pachonjcl** [comment]
Were you able to solve this?

**Comment by karlbunnell** [comment]
Nope, never heard from the author on this one.

**Comment by oprokidnev** [comment]
@karlbunnell This project was created while angular 2 was in beta dev stage. The best way for you right now is to clone original [angular2 seed](/angular/angular2-seed) repository and try to gather everything together yourself.

**Comment by karlbunnell** [comment]
Will do. Thanks for your response!
